# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d9b7e53f840608d9605bac1a42239ba107b5526e3936ec771d593873c1383e01819991b727aa8780164b8a1dd1df5dd42fe25464c05b2dca4f5a918508160fff

test:
  secret_key_base: 8182f0cabb64e092b6e38b3b635a479ad9e23addd5cd38a4926e5e3f842848dba4a5c3504317cc30626e7619d945659cacaf069f7f491b4d33d8d3cfc2387969

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
